/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ClubForm.module.css";

function ClubForm() {
  return (
    <form className={styles.clubForm}>
      <div className={styles.formGroup}>
        <label htmlFor="clubName" className={styles.formLabel}>
          Tên câu lạc bộ
        </label>
        <input
          type="text"
          id="clubName"
          className={styles.formInput}
          required
        />
      </div>
      <div className={styles.formGroup}>
        <label htmlFor="clubDescription" className={styles.formLabel}>
          Mô tả
        </label>
        <textarea
          id="clubDescription"
          className={styles.formTextarea}
          required
        ></textarea>
      </div>
    </form>
  );
}

export default ClubForm;
