/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SkillLevelSelection.module.css";

const skillLevels = [
  "Mới biết chơi",
  "Trung bình - Khá",
  "Chuyên nghiệp",
  "Tất cả trình độ",
];

function SkillLevelSelection() {
  return (
    <section className={styles.skillLevelSelection}>
      <h2 className={styles.sectionTitle}>Trình độ thể thao</h2>
      <div className={styles.skillLevelGrid}>
        {skillLevels.map((level, index) => (
          <button key={index} className={styles.skillLevelButton}>
            {level}
          </button>
        ))}
      </div>
    </section>
  );
}

export default SkillLevelSelection;
