/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SportSelection.module.css";

const sports = [
  { emoji: "⚽", name: "Bóng đá" },
  { emoji: "🏐", name: "Bóng chuyền" },
  { emoji: "🏀", name: "Bóng rổ" },
  { emoji: "🏸", name: "Cầu lông" },
  { emoji: "🥒", name: "Pickleball" },
  { emoji: "🎱", name: "Bida" },
];

function SportSelection() {
  return (
    <section className={styles.sportSelection}>
      <h2 className={styles.sectionTitle}>Chọn môn thể thao</h2>
      <div className={styles.sportGrid}>
        {sports.map((sport, index) => (
          <button key={index} className={styles.sportButton}>
            <span className={styles.sportEmoji}>{sport.emoji}</span>
            <span className={styles.sportName}>{sport.name}</span>
          </button>
        ))}
      </div>
    </section>
  );
}

export default SportSelection;
